#!/bin/sh
# Removes the files generated by running BCPGPTest (mvn compile exec:java) and the Maven
# build output. Input files (test.txt, legacy-test.txt.signed.asc and the keys) are left alone.

cd "$(dirname "$0")" || exit 1

rm -fv \
    test.txt.enc \
    test.txt.dec \
    test.txt.signed.enc \
    test.txt.signed.dec \
    test.txt.signed.enc.asc \
    test.txt.signed.armored.dec \
    test.txt.signed.dec1 \
    test.txt.signed.dec2

if [ -d target ]; then
    rm -rf target && echo "removed 'target'"
fi
